# Generated by Django 5.2.8 on 2026-06-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='veterinaria.cita'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
