# Generated by Django 5.2.8 on 2026-06-18 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_alter_cita_estado_cita_motivo_consulta_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='veterinario',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='propietario',
        ),
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Contactado', 'Contactado'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='veterinaria.tipoconsulta')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='veterinaria.veterinario')),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
