# Generated by Django 5.2.8 on 2026-06-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_remove_consulta_cita_remove_consulta_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='veterinaria.solicitudcita')),
            ],
        ),
    ]
