# Generated by Django 5.2.8 on 2026-06-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_alter_solicitudcita_telefono_fichamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='edad_mascota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='especie',
            field=models.CharField(default='No especifica', max_length=50),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='raza',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
