# Generated by Django 5.2.8 on 2026-06-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_fichamedica_edad_mascota_fichamedica_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='fecha_hora',
            field=models.DateTimeField(unique=True),
        ),
    ]
