# Generated by Django 5.2.8 on 2026-06-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0006_alter_solicitudcita_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcita',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
