# Generated by Django 6.0.6 on 2026-06-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0008_alter_solicitudcita_veterinario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='monto_pagado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='webpay_orden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='webpay_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
